%%
% setup of both TT-Toolbox and TAPAS
%%
cd ../../TT-Toolbox/
setup
cd ../tapas/
setup
cd examples/
%%
% set parameters
%%
n = 3; % number of submodels

l1 = 8.333e-2;
d2 = 8.333e-2;
m1 = 0.5;
m2 = 0.5;
m3 = 0.5;
d1 = n/2;
t3 = 1;
%%
% define the infinitesimal generator matrix implicitly
%%
sz = [3 3 4]; % sizes of the submodels
R = cell(1, n);
W = cell(2, n);
R{1} = tt_matrix([0   l1 0; ...
                  m1  0  0; ...
                  0   0  0]);
R{2} = tt_matrix([0   0  0; ...
                  m2  0  0;
                  0   0  0]);
R{3} = tt_matrix([0   0  0 0; ...
                  m3  0  0 t3; ...
                  0   0  0 0; ...
                  0   0  0 0]);

W{1,1} = tt_matrix([0  0  0; ...
                    0  0  d1; ...
                    0  0  0]);
W{1,2} = tt_matrix([0  0  0; ...
                    0  0  1; ...
                    0  0  0]);
W{1,3} = tt_matrix([0  0  1  0; ...
                    0  0  1  0; ...
                    0  0  0  0; ...
                    0  0  0  1]);

W{2,1} = tt_matrix([1  0  0; ...
                    0  1  0; ...
                    0  0  1]);
W{2,2} = tt_matrix([0  d2  0; ...
                    0  0   0; ...
                    0  0   0]);
W{2,3} = tt_matrix([0  1  0  0; ...
                    0  0  0  0; ...
                    0  0  0  0; ...
                    0  0  0  1]);
%%
% define absorbing states of interest
%%
F = [3 3 3];
B = [3 3 4];
absorbing_states =[F; B];
%%
% define initial probability and reward vectors
%%
pi0 = ktt_ej(sz, ones(1, n));
r   = round(ktt_ones(sz) - ktt_ej(sz, F) - ktt_ej(sz, B), 1.e-8);
%%
% set tolerances
%%
ttol = 1e-12;
tol = 1e-4;
%%
% evaluate the measures
%%

method = 'gmres';

[MTTF, timeMTTF] = eval_measure('inv', pi0, r, R, W, 'debug', false, ...
				    'algorithm', method, 'ttol', ttol,  ...
				    'absorbing_states', absorbing_states, 'tol', tol);                
[CMTTF, timeCMTTF] = eval_measure('cond_etta', pi0, r, R, W, 'debug', false, ...
		 			         'algorithm', method, ...
    				          'absorbing_states', absorbing_states, ...
					          'conditional_indices', F, ...
					          'ttol', ttol, 'tol', tol);
[CMTTB, timeCMTTB] = eval_measure('cond_etta', pi0, r, R, W, 'debug', false, ...
		 			         'algorithm', method, ...
    				          'absorbing_states', absorbing_states, ...
					          'conditional_indices', B, ...
					          'ttol', ttol, 'tol', tol);
fprintf("\n\n\n");
fprintf("Summary:\n");
fprintf("MTTF = %f (time %fs), CMTTF = %f (time %fs), CMTTB = %f (time %fs)\n", MTTF, timeMTTF, CMTTF, timeCMTTF, CMTTB, timeCMTTB);